version: "3.8"

services:
  web:
    image: "worky:latest"
    container_name: "worky"
    restart: always
    command: sh ./scripts/start-prod.sh
    build:
      target: production
      context: .
      dockerfile: Dockerfile
    volumes:
      - django_static:/home/worky/web/static
      - django_media:/home/worky/web/media
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: "postgres:14-alpine"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - django_static:/home/worky/web/static
      - django_media:/home/worky/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  pgdata:
  django_static:
  django_media:
