# Generated by Django 4.0.5 on 2022-06-08 03:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=50, verbose_name='Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('job', models.CharField(choices=[('S', 'Software Engineer'), ('D', 'Data Analyst'), ('Q', 'Quality Assurance'), ('M', 'Manager'), ('P', 'Project Manager'), ('E', 'Executive')], max_length=1, verbose_name='Job')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employees/avatars/', verbose_name='Avatar')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('skills', models.ManyToManyField(to='employees.skills')),
            ],
        ),
    ]
